export const REQUEST_ALL_DATA = 'REQUEST_ALL_DATA';
export const ALL_DATA_SUCCESS = 'ALL_DATA_SUCCESS';
export const REQUEST_DELETE_CONTACT = 'REQUEST_DELETE_CONTACT';
export const REQUEST_EDIT_CONTACT = 'REQUEST_EDIT_CONTACT';
export const REQUEST_ADD_CONTACT = 'REQUEST_ADD_CONTACT';