# Generated by Django 2.1.4 on 2020-10-09 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='data',
            name='gender',
        ),
    ]
